spring:
  profiles:
    active: @profileActive@,jdbc-@profileActive@
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
logging:
  config: classpath:logback.xml
  path: logs
  level: info
